# Generated by Django 4.2.1 on 2024-02-09 00:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=45, null=True)),
                ('content', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('intent', models.TextField(null=True)),
                ('subject_of_interest', models.CharField(max_length=200, null=True)),
                ('session', models.CharField(max_length=100)),
                ('stitches', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('last_interaction', models.DateTimeField(null=True)),
                ('started_by', models.CharField(max_length=100, null=True)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('friendly_summary', models.TextField(null=True)),
                ('channel', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
                ('busy', models.BooleanField(default=False)),
                ('multimessage', models.BooleanField(default=False)),
                ('experience', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
    ]
