# Generated by Django 4.2.1 on 2024-02-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='multimessage',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('closed', 'Closed')], default='waiting', max_length=20),
        ),
    ]
